### ISSUE TITLE
Add multi network support to `graph-network-indexer` chart

### ISSUE THREAD

**Issue by calinah** [graphops/launchpad-charts#110]
`v0.20.18` of `indexer-agent` comes with capacity for the Agent to interact with multiple protocol networks (blockchains that host The Graph Protocol) by running a single instance of the indexer-agent program. We need to adapt chart to be able to support various configs for various chains. See https://github.com/graphprotocol/indexer/releases/tag/v0.20.18

**Comment by cjorge-graphops** [comment]
is this still relevant? @calinah

**Comment by cjorge-graphops** [comment]
Closing because no longer relevant I think, can be re-opened if need be
