### ISSUE TITLE
No metrics from `subgraph-radio`

### ISSUE THREAD

**Issue by aasseman** [graphops/launchpad-charts#278]
I'm getting a 404 error on port 2384, and Prometheus also gets nothing.
I checked the pod settings:
- command argument `--metrics-host=0.0.0.0` is there
- Env var `METRICS_PORT=2384` is there.
- The logs say `INFO subgraph_radio::metrics: Prometheus Metrics port exposed, address: "0.0.0.0:2384"`

Using `subgraph-radio:1.0.2`

**Comment by cjorge-graphops** [comment]
Hey @aasseman, I can confirm "works on my computer", as I've tested the metrics endpoints on both versions 1.0.1 and 1.0.2. In the cluster context (pod to pod) or with port-forwarding, doing a curl to `http://subgraph-radio:2384/metrics` is working fine in those tests.

Is it possible it can be something related to your environment? network policies, or something else. I'm gonna tag Petko as well, as he may have some ideas of what may be amiss or what scenarios, if any, metrics endpoint may be failing @axiomatic-aardvark

**Comment by axiomatic-aardvark** [comment]
Unfortunately I'm also not sure why it wouldn't be working :( metrics on `1.0.2` are also working fine for me both locally and in Payne's docker-compose setup

**Comment by aasseman** [comment]
Ah, I wasn't poking at the `/metrics` path when testing directly... It does work indeed.
I only have issues with the grafana dashboard now, but I'll figure it out.
