### ISSUE TITLE
subgraph-availability-oracle image tag

### ISSUE THREAD

**Issue by cjorge-graphops** [graphops/launchpad-charts#307]
Upstream does not use versioning for SAO.

The chart has by default `imagePullPolicy: ifNotAvailable`, meaning it won't be updated (unless on a Node change or otherwise the image is missing locally).

We should change from using a tag to use digests for this chart to bring it in line with the lifecycle/release standard of the other charts. May also require some Renovate adjustments.

**Comment by calinah** [comment]
this is no longer relevant as SAO has implemented releases. Instead we'll add versions as per current renovate pattern https://github.com/graphops/launchpad-charts/pull/317
