### ISSUE TITLE
tap-agent should be Statefulset, not scalable

### ISSUE THREAD

**Issue by aasseman** [graphops/launchpad-charts#350]
For TAP to work correctly, exactly 1 instance of tap-agent should run at all times. Therefore if should be a statefulset, and this option should be removed:
https://github.com/graphops/launchpad-charts/blob/a1548a901cf05a61c613c1ec5440d60b6d474b62/charts/graph-network-indexer/values.yaml#L283

(like indexer-agent)

**Comment by cjorge-graphops** [comment]
@aasseman very true, thank you for spotting that! 🙇 Will be changed soon

@calinah

**Comment by calinah** [comment]
addressed by https://github.com/graphops/launchpad-charts/pull/351
