### ISSUE TITLE
Document the release workflow in the README

### ISSUE THREAD

**Issue by chriswessels** [graphops/launchpad-charts#89]
- Timeline:
    - New dependency released
    - Renovate opens PR updating (e.g. appVersion)
        - CI runs on branch, pushes canary release
        - Commit is added to branch, setting stable version
    - PR is merged into `main`, which actually makes GitHub stable release

**Comment by cjorge-graphops** [comment]
Closed by https://github.com/graphops/launchpad-charts/pull/204
