### ISSUE TITLE
Bug(subgraph-radio): Node P2P port functionality isn't working

### ISSUE THREAD

**Issue by chriswessels** [graphops/launchpad-charts#91]
Existing p2pNodePort functionality only allows exposing a single P2P port, but this chart specifies two:
https://github.com/graphops/launchpad-charts/blob/main/charts/subgraph-radio/values.yaml#L106-L112

All of the init container machinery also only supports a single port:
https://github.com/graphops/launchpad-charts/blob/main/charts/subgraph-radio/templates/subgraph-radio/statefulset.yaml#L68-L74

I think we need to reimplement this functionality by referencing another p2pNodePort-enabled chart

**Comment by calinah** [comment]
fixed by #130 applied the same to #131
